version: "3.8"

networks:
  shared_network:
    name: shared_network

services:
  postgres-zoomcamp:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
      POSTGRES_DB: postgres-zoomcamp
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared_network
volumes:
  postgres-data: